### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ritu-2001**
I am adding a template of sign up form,,, Please merge my PR it's my first  contribution ,,,,, i will get confidence for my future work

### CODE REVIEW

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
Hello, @Ritu-2001 You are doing a great job. 
Just do one thing put all those styles in the head tag. 
The only body contains the visual part of a website.

**Comment by Ritu-2001** [comment]
Sorry, But  i don't get your words

**Comment by Ritu-2001** [comment]
ok

**Comment by Ritu-2001** [comment]
add all styles in head tag and keep body only contains visual part of website as per you say

**Comment by Diptenusarkar** [comment]
Put Then In a Folder 📁 like others do.

**Pull request closed without merging**
