### PR TITLE
fixed the issue #324

### PR DESCRIPTION
**Pull request by GitPratyush**
@Diptenusarkar  I added the QR_CODE_GENERATOR using node js. Accept my PR with a label of hacktoberfest.

### CODE REVIEW

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
1. Fix Run Problem or Add Run Script.
2. Remove **node_modules** and **package-lock.json** 
2. Add **.gitignore** file.

**Review by GitPratyush — COMMENTED** [review]
@Diptenusarkar as you mentioned earlier for the necessary changes 
plz review it.

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
It would be best if you fixed it. 
My First Question how do we run this project?
Screenshot (1312)

**Comment by GitPratyush** [comment]
@Diptenusarkar  i have mentioned the steps in my readme file however i am explaining here step by step:-

examples

After clonning and opening the folder 
Command 1:- cd QR_CODE_GENERATOR
Command 2:- npm install
Command 3- node .\index.js

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
