### PR TITLE
added Loading Animation Button Template #351

### LINKED ISSUE #351: Loading Button Animations Template
Please let me know if you find any issues 
Please assign it under the hacktober fest , i want to work under it 

**Is your feature request related to a problem? Please describe.**
sometimes we can show the user the loading instead of directly moving to other page 

**Describe the solution you'd like**
this button looks cool

### PR DESCRIPTION
**Pull request by Surya-V-28**
Closes #351 ,

Please let me know if there is any issues

Please assign this to hacktober fest 
 
I would to slove if there is any issues 

samples 
image
Onclick each button has  the different animations 

video link is here 

https://drive.google.com/file/d/1K6FF2wxF7SCL_ZBGzM75bnu4fNJraZXe/view?usp=sharing

### CODE REVIEW

**Comment by Surya-V-28** [comment]
I am wondering what is tthis CodeQL check for  ?

**Review by Diptenusarkar — APPROVED** [review]

**Comment by Diptenusarkar** [comment]
CodeQL check is enabled by default.
If you are using any CDN link and it's an outdated link it will inform us. Also, helps us keep up-to-date npm dependence.

**Comment by Surya-V-28** [comment]
@Diptenusarkar, thanks for sharing the information

**Comment by Diptenusarkar** [comment]
Your Are Welcome 🤗

**Pull request merged**
