### PR TITLE
feat: adding simple-gallery web

### PR DESCRIPTION
**Pull request by albimdkr**

### CODE REVIEW

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
Screenshot (1314)
Need to fix

**Comment by albimdkr** [comment]
ah I see, will be fix it

**Comment by albimdkr** [comment]
Dude, what I do next? After I fix the code? PR again or what? sorry to say that I'm a beginner using the git

**Comment by Diptenusarkar** [comment]
As I can See ther is some images.
But There is a problem to display image.

**Comment by albimdkr** [comment]
> fix: location img
yeah, I just finished to fix it, this message commit "fix: location img"

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
