### PR TITLE
Added my library management system

### PR DESCRIPTION
**Pull request by ratneshgupta01**
I added my project on library management system, solves #132

### CODE REVIEW

**Comment by ratneshgupta01** [comment]
Sir, please merge this under hacktoberfest 2022

**Comment by Diptenusarkar** [comment]
Sure sir, Just i need check before

**Comment by ratneshgupta01** [comment]
cool! plz do let me know.

**Review by Diptenusarkar — APPROVED** [review]

**Comment by Diptenusarkar** [comment]
Remove error

**Comment by ratneshgupta01** [comment]
@Diptenusarkar actually there is no error in the code, the bot of github gives error in some cases due to its pre-deterministic feature. For example this is pointing out user as root is hard-coded but that's what is used in while running the app, I can't change that.

**Pull request merged**
