### PR TITLE
PLACEMENT PREPARATION ROADMAP position updated  

### PR DESCRIPTION
**Pull request by Swastik200**
PLZ CHECK AND CONFIRM

### CODE REVIEW

**Comment by Swastik200** [comment]
> Fix Background Image position

plz check now and confirm

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
Fix Background Image position

**Comment by Swastik200** [comment]
Done.
What to do now plz tell

**Comment by Diptenusarkar** [comment]
> Fix Background Image position

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
