### PR TITLE
add: food delivery template

### LINKED ISSUE #408: Food delivery website
A food delivery website for only college campus.

### PR DESCRIPTION
**Pull request by sudhanshugautam2911**
Description
Added a food delivery website

Closes #408

Tech Stack Used
ReactJs
Tailwind CSS
Firebase

Screenshot
image
image

### CODE REVIEW

**Comment by sudhanshugautam2911** [comment]
please checkout the PR, @diptenusarkar

**Review by Diptenusarkar — COMMENTED** [review]
What did you change

**Comment by sudhanshugautam2911** [comment]
I have added complete food delivery website

**Comment by sudhanshugautam2911** [comment]
I also added my food delivery template in readme file, please tell me if it was not required.

**Comment by Diptenusarkar** [comment]
I'm unable to see this

**Comment by sudhanshugautam2911** [comment]
I think there is some issue with commit, give me some time to fix it

**Comment by sudhanshugautam2911** [comment]
@Diptenusarkar  I think now everything is okay.

**Comment by sudhanshugautam2911** [comment]
Is there something wrong?

**Comment by Diptenusarkar** [comment]
Product Display problem
Screenshot (1315)

**Comment by Diptenusarkar** [comment]
Exactly, I do this. but not working for me.

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
